### ISSUE TITLE
Update Scale Up and Scale down policies

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#44]
Update all scale up and scale down policies used in stakater, 

Possible scale up policy: add 1 instance on 80-90% of CPU Utilization

**Comment by hamza3202** [comment]
We have updated our scaling policies to change based on number of instances provided rather than percentage increase
We add or remove 1 instance if the scaling up/down policy is activated
For scaling up we see if CPU utilization is 80% or more for 2 minutes
For scaling down we see if CPU utilization is 50% or less for 30 minutes

This issue has been resolved with following pull requests:
https://github.com/stakater/prod-deployment-reference/pull/7
https://github.com/stakater/infrastructure-reference/pull/26
https://github.com/stakater/prod-deployment-reference/pull/6

**Comment by hamza3202** [comment]
New Auto scaling Group was created when we switched the prod in this release
